# Generated by Django 4.2.20 on 2025-05-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_property'),
        ('bookings', '0002_remove_booking_user_email_remove_booking_user_name_and_more'),
    ]

    operations = [
    ]
